# Workflow pour construire et déployer un site Hugo sur GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Lance le workflow à chaque push sur la branche main/master
  push:
    branches:
      - master
      - main

  # Permet de lancer manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définit les permissions nécessaires pour déployer sur GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permet un seul déploiement concurrent
concurrency:
  group: "pages"
  cancel-in-progress: false

# Paramètres par défaut pour les commandes shell
defaults:
  run:
    shell: bash

jobs:
  # Job de construction
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.151.2
    steps:
      - name: Installer Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Installer Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configurer Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Installer les dépendances Node.js
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Construire avec Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Uploader l'artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Job de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
